import { Category } from '@/types/problem';

// 백준 - DFS/BFS, 다익스트라, 트리
// 프로그래머스 DFS/BFS/그래프
// 프로그래머스 lv2,3,4
// 리트코드 150 - Array/String, 백트래킹, Heap, Stack, Hashmap, Graph, Graph BFS

export const categories3: Category[] = [
	{
		name: 'ALL',
		problems: [
			{
				id: 1,
				title: '최소 직사각형',
				difficulty: 'Easy',
				completed: true,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/86491',
				platform: 'Programmers',
			},
			{
				id: 2,
				title: '소수 찾기',
				difficulty: 'Easy',
				completed: true,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42839',
				platform: 'Programmers',
			},
			{
				id: 3,
				title: '조이스틱',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42860',
				platform: 'Programmers',
			},
			{
				id: 4,
				title: '모의고사',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42840',
				platform: 'Programmers',
			},
			{
				id: 5,
				title: '카펫',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42842',
				platform: 'Programmers',
			},
			{
				id: 6,
				title: '피로도',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/87946',
				platform: 'Programmers',
			},
			{
				id: 7,
				title: '전력망을 둘로 나누기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/86971',
				platform: 'Programmers',
			},
			{
				id: 8,
				title: '모음사전',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/84512',
				platform: 'Programmers',
			},
			{
				id: 9,
				title: '숫자야구',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/2503',
				platform: 'Baekjoon',
			},
			{
				id: 10,
				title: '체육복',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42862',
				platform: 'Programmers',
			},
			{
				id: 11,
				title: '큰 수 만들기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42883',
				platform: 'Programmers',
			},
			{
				id: 12,
				title: '구명보트',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42885',
				platform: 'Programmers',
			},
			{
				id: 13,
				title: '섬 연결하기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42861',
				platform: 'Programmers',
			},
			{
				id: 14,
				title: '단속카메라',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42884',
				platform: 'Programmers',
			},
			{
				id: 15,
				title: '거스름돈',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/12907',
				platform: 'Programmers',
			},
			{
				id: 16,
				title: '부분수열의 합',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1182',
				platform: 'Baekjoon',
			},
			{
				id: 17,
				title: '행운의 문자열',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1342',
				platform: 'Baekjoon',
			},
			{
				id: 18,
				title: '거스름돈',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/5585',
				platform: 'Baekjoon',
			},
			{
				id: 19,
				title: '보물',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1026',
				platform: 'Baekjoon',
			},
			{
				id: 20,
				title: '도서관',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1461',
				platform: 'Baekjoon',
			},
			{
				id: 21,
				title: '같은 숫자는 싫어',
				difficulty: 'Easy',
				completed: true,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/12906',
				platform: 'Programmers',
			},
			{
				id: 22,
				title: '기능개발',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42586',
				platform: 'Programmers',
			},
			{
				id: 23,
				title: '올바른 괄호',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/12909',
				platform: 'Programmers',
			},
			{
				id: 24,
				title: '프로세스',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42587',
				platform: 'Programmers',
			},
			{
				id: 25,
				title: '다리를 지나는 트럭',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42583',
				platform: 'Programmers',
			},
			{
				id: 26,
				title: '주식가격',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42584',
				platform: 'Programmers',
			},
			{
				id: 27,
				title: '더 맵게',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42626',
				platform: 'Programmers',
			},
			{
				id: 28,
				title: '디스크 컨트롤러',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42627',
				platform: 'Programmers',
			},
			{
				id: 29,
				title: '이중 우선순위큐',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42628',
				platform: 'Programmers',
			},
			{
				id: 30,
				title: '완주하지 못한 선수',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42576',
				platform: 'Programmers',
			},
			{
				id: 31,
				title: '폰켓몬',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/1845',
				platform: 'Programmers',
			},
			{
				id: 32,
				title: '전화번호 목록',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42577',
				platform: 'Programmers',
			},
			{
				id: 33,
				title: '의상',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42578',
				platform: 'Programmers',
			},
			{
				id: 34,
				title: '베스트앨범',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42579',
				platform: 'Programmers',
			},
			{
				id: 35,
				title: '정렬',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42748',
				platform: 'Programmers',
			},
			{
				id: 36,
				title: '가장 큰 수',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42746',
				platform: 'Programmers',
			},
			{
				id: 37,
				title: 'H-Index',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42747',
				platform: 'Programmers',
			},
			{
				id: 38,
				title: '입국심사',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/43238',
				platform: 'Programmers',
			},
			{
				id: 39,
				title: '징검다리',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/43236',
				platform: 'Programmers',
			},
		],
	},
	{
		name: 'Tree/DFS/BFS/Graph/MST/Kruskal/Union-Find/Prim',
		problems: [
			{
				id: 1,
				title: 'DFS와 BFS',
				difficulty: 'Easy',
				completed: true,
				link: 'https://www.acmicpc.net/problem/1260',
				platform: 'Baekjoon',
			},
			{
				id: 2,
				title: '최단경로',
				difficulty: 'Easy',
				completed: true,
				link: 'https://www.acmicpc.net/problem/1753',
				platform: 'Baekjoon',
			},
			{
				id: 3,
				title: '섬 연결하기',
				difficulty: 'Easy',
				completed: true,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42861',
				platform: 'Programmers',
			},
			{
				id: 4,
				title: '트리 순회',
				difficulty: 'Easy',
				completed: true,
				link: 'https://www.acmicpc.net/problem/1991',
				platform: 'Baekjoon',
			},
		],
	},
];

/*
{
				id: 16,
				title: '택배 배달과 수거하기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/150369',
				platform: 'Programmers',
			},
			{
				id: 17,
				title: 'Car Pooling',
				difficulty: 'Easy',
				completed: false,
				link: 'https://leetcode.com/problems/car-pooling/description',
				platform: 'LeetCode',
			},
			{
				id: 18,
				title: '쿠키 구입',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/49995',
				platform: 'Programmers',
			},
			{
				id: 19,
				title: 'Longest Happy String',
				difficulty: 'Easy',
				completed: false,
				link: 'https://leetcode.com/problems/longest-happy-string/description',
				platform: 'LeetCode',
			},
			{
				id: 25,
				title: 'RGB거리',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1149',
				platform: 'Baekjoon',
			},
			{
				id: 26,
				title: '가장 긴 증가하는 부분 수열',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/11053',
				platform: 'Baekjoon',
			},
			{
				id: 27,
				title: 'LCS',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/9251',
				platform: 'Baekjoon',
			},
			{
				id: 28,
				title: '평범한 배낭',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/12865',
				platform: 'Baekjoon',
			},
			{
				id: 29,
				title: '구간 합 구하기4',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/11659',
				platform: 'Baekjoon',
			},
			{
				id: 30,
				title: '구간 합 구하기5',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/11660',
				platform: 'Baekjoon',
			},
			{
				id: 49,
				title: 'N으로 표현',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42895',
				platform: 'Programmers',
			},
			{
				id: 51,
				title: '정수 삼각형',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/43105',
				platform: 'Programmers',
			},
			{
				id: 52,
				title: '등굣길',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42898',
				platform: 'Programmers',
			},
			{
				id: 53,
				title: '사칙연산',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/1843',
				platform: 'Programmers',
			},
			{
				id: 54,
				title: '도둑질',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42897',
				platform: 'Programmers',
			},
			{
				id: 55,
				title: '칸토어 집합',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/4779',
				platform: 'Baekjoon',
			},
			{
				id: 56,
				title: '로또',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/6603',
				platform: 'Baekjoon',
			},
			{
				id: 57,
				title: '암호 만들기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1759',
				platform: 'Baekjoon',
			},
			{
				id: 58,
				title: '모든 순열',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/10974',
				platform: 'Baekjoon',
			},
			{
				id: 59,
				title: '좌표 정렬하기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/11650',
				platform: 'Baekjoon',
			},
			{
				id: 60,
				title: 'Sport Climbing Combined',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/23246',
				platform: 'Baekjoon',
			},
			{
				id: 61,
				title: '체스판 다시 칠하기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1018',
				platform: 'Baekjoon',
			},
			{
				id: 62,
				title: '사탕 게임',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/3085',
				platform: 'Baekjoon',
			},
			{
				id: 63,
				title: '연속합',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1912',
				platform: 'Baekjoon',
			},
			{
				id: 64,
				title: '2×n 타일링',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/11726',
				platform: 'Baekjoon',
			},
			{
				id: 65,
				title: '알파벳',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1987',
				platform: 'Baekjoon',
			},
			{
				id: 66,
				title: '스도쿠',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/2580',
				platform: 'Baekjoon',
			},
			{
				id: 67,
				title: '가장 긴 바이토닉 부분 수열',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/11054',
				platform: 'Baekjoon',
			},
			{
				id: 68,
				title: '앱',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/7579',
				platform: 'Baekjoon',
			},
			{
				id: 69,
				title: '회의실 배정',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1931',
				platform: 'Baekjoon',
			},
			{
				id: 70,
				title: '타일 채우기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/2133',
				platform: 'Baekjoon',
			},
			{
				id: 71,
				title: '수 찾기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1920',
				platform: 'Baekjoon',
			},
			{
				id: 72,
				title: '개똥벌레',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/3020',
				platform: 'Baekjoon',
			},
			{
				id: 73,
				title: '공유기 설치',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/2110',
				platform: 'Baekjoon',
			},
			{
				id: 74,
				title: '구간 나누기2',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/13397',
				platform: 'Baekjoon',
			},
			{
				id: 75,
				title: '부분합',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1806',
				platform: 'Baekjoon',
			},
			{
				id: 76,
				title: '회문',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/17609',
				platform: 'Baekjoon',
			},
*/
