import { Category } from '@/types/problem';

// 백준 - 브루트포스/그리디/DP 실전 문제
// 리트코드 150 - Array/String, 백트래킹, Heap, Stack, Hashmap, Graph, Graph BFS
// 50시간 - 50문제
// 추가 문제집 - 프로그래머스 lv2,3

export const categories3: Category[] = [
	{
		name: 'ALL',
		problems: [
			{
				id: 1,
				title: '최소 직사각형',
				difficulty: 'Easy',
				completed: true,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/86491',
				platform: 'Programmers',
			},
			{
				id: 2,
				title: '소수 찾기',
				difficulty: 'Easy',
				completed: true,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42839',
				platform: 'Programmers',
			},
			{
				id: 3,
				title: '조이스틱',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42860',
				platform: 'Programmers',
			},
			{
				id: 4,
				title: '모의고사',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42840',
				platform: 'Programmers',
			},
			{
				id: 5,
				title: '카펫',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42842',
				platform: 'Programmers',
			},
			{
				id: 6,
				title: '피로도',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/87946',
				platform: 'Programmers',
			},
			{
				id: 7,
				title: '전력망을 둘로 나누기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/86971',
				platform: 'Programmers',
			},
			{
				id: 8,
				title: '모음사전',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/84512',
				platform: 'Programmers',
			},
			{
				id: 9,
				title: '숫자야구',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/2503',
				platform: 'Baekjoon',
			},
			{
				id: 10,
				title: '체육복',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42862',
				platform: 'Programmers',
			},
			{
				id: 11,
				title: '큰 수 만들기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42883',
				platform: 'Programmers',
			},
			{
				id: 12,
				title: '구명보트',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42885',
				platform: 'Programmers',
			},
			{
				id: 13,
				title: '섬 연결하기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42861',
				platform: 'Programmers',
			},
			{
				id: 14,
				title: '단속카메라',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42884',
				platform: 'Programmers',
			},
			{
				id: 15,
				title: '거스름돈',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/12907',
				platform: 'Programmers',
			},
			{
				id: 16,
				title: '택배 배달과 수거하기',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/150369',
				platform: 'Programmers',
			},
			{
				id: 17,
				title: 'Car Pooling',
				difficulty: 'Easy',
				completed: false,
				link: 'https://leetcode.com/problems/car-pooling/description',
				platform: 'LeetCode',
			},
			{
				id: 18,
				title: '쿠키 구입',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/49995',
				platform: 'Programmers',
			},
			{
				id: 19,
				title: 'Longest Happy String',
				difficulty: 'Easy',
				completed: false,
				link: 'https://leetcode.com/problems/longest-happy-string/description',
				platform: 'LeetCode',
			},
			{
				id: 20,
				title: '부분수열의 합',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1182',
				platform: 'Baekjoon',
			},
			{
				id: 21,
				title: '행운의 문자열',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1342',
				platform: 'Baekjoon',
			},
			{
				id: 22,
				title: '거스름돈',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/5585',
				platform: 'Baekjoon',
			},
			{
				id: 23,
				title: '보물',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1026',
				platform: 'Baekjoon',
			},
			{
				id: 24,
				title: '도서관',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1461',
				platform: 'Baekjoon',
			},
			{
				id: 25,
				title: 'RGB거리',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/1149',
				platform: 'Baekjoon',
			},
			{
				id: 26,
				title: '가장 긴 증가하는 부분 수열',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/11053',
				platform: 'Baekjoon',
			},
			{
				id: 27,
				title: 'LCS',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/9251',
				platform: 'Baekjoon',
			},
			{
				id: 28,
				title: '평범한 배낭',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/12865',
				platform: 'Baekjoon',
			},
			{
				id: 29,
				title: '구간 합 구하기4',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/11659',
				platform: 'Baekjoon',
			},
			{
				id: 30,
				title: '구간 합 구하기5',
				difficulty: 'Easy',
				completed: false,
				link: 'https://www.acmicpc.net/problem/11660',
				platform: 'Baekjoon',
			},
			{
				id: 31,
				title: '같은 숫자는 싫어',
				difficulty: 'Easy',
				completed: true,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/12906',
				platform: 'Programmers',
			},
			{
				id: 32,
				title: '기능개발',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42586',
				platform: 'Programmers',
			},
			{
				id: 33,
				title: '올바른 괄호',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/12909',
				platform: 'Programmers',
			},
			{
				id: 33,
				title: '프로세스',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42587',
				platform: 'Programmers',
			},
			{
				id: 34,
				title: '다리를 지나는 트럭',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42583',
				platform: 'Programmers',
			},
			{
				id: 35,
				title: '주식가격',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42584',
				platform: 'Programmers',
			},
			{
				id: 36,
				title: '더 맵게',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42626',
				platform: 'Programmers',
			},
			{
				id: 37,
				title: '디스크 컨트롤러',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42627',
				platform: 'Programmers',
			},
			{
				id: 38,
				title: '이중 우선순위큐',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42628',
				platform: 'Programmers',
			},
			{
				id: 39,
				title: '완주하지 못한 선수',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42576',
				platform: 'Programmers',
			},
			{
				id: 40,
				title: '폰켓몬',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/1845',
				platform: 'Programmers',
			},
			{
				id: 41,
				title: '전화번호 목록',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42577',
				platform: 'Programmers',
			},
			{
				id: 42,
				title: '의상',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42578',
				platform: 'Programmers',
			},
			{
				id: 43,
				title: '베스트앨범',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42579',
				platform: 'Programmers',
			},
			{
				id: 44,
				title: '정렬',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42748',
				platform: 'Programmers',
			},
			{
				id: 45,
				title: '가장 큰 수',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42746',
				platform: 'Programmers',
			},
			{
				id: 46,
				title: 'H-Index',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42747',
				platform: 'Programmers',
			},
			{
				id: 47,
				title: '입국심사',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/43238',
				platform: 'Programmers',
			},
			{
				id: 48,
				title: '징검다리',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/43236',
				platform: 'Programmers',
			},
			{
				id: 49,
				title: 'N으로 표현',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42895',
				platform: 'Programmers',
			},
			{
				id: 50,
				title: 'N으로 표현',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42895',
				platform: 'Programmers',
			},
			{
				id: 51,
				title: '정수 삼각형',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/43105',
				platform: 'Programmers',
			},
			{
				id: 52,
				title: '등굣길',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42898',
				platform: 'Programmers',
			},
			{
				id: 53,
				title: '사칙연산',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/1843',
				platform: 'Programmers',
			},
			{
				id: 54,
				title: '도둑질',
				difficulty: 'Easy',
				completed: false,
				link: 'https://school.programmers.co.kr/learn/courses/30/lessons/42897',
				platform: 'Programmers',
			},
		],
	},
];
